Changes discovery_datatool scripts to use datatool.properties (ala discovery.properties).

diff --git a/stage/bin/datatool-spawner b/stage/bin/datatool-spawner
--- a/stage/bin/datatool-spawner
+++ b/stage/bin/datatool-spawner
@@ -56,6 +56,12 @@ function log_rotate {
   unset LOG_NAME LOG_MAX LOG_NUM
 }
 
+# obtain discovery_datatool property values
+function get_property() {
+  if [ $(grep -c "^ *$1 *=" datatool.properties ) -gt 0 ]; then
+    grep "^ *$1 *=" datatool.properties | sed "s/^ *$1 *= *\([^ ]*\)/\1/"
+  fi
+}
 #
 # Enter the datatool working directory and remain there for the
 # rest of this script.
@@ -63,8 +69,8 @@ function log_rotate {
 
 cd "$DATATOOL_DIR"
 
-if [ ! -f discovery_datatool.xml ]; then
-  echo "The discovery_datatool.xml file is missing from $(pwd)" >&2
+if [ ! -f datatool.properties ]; then
+  echo "The datatool.properties file is missing from $(pwd)" >&2
   exit 1
 fi
 
@@ -87,43 +93,71 @@ fi
 # Set some sensible defaults
 #
 
+# jvm.cmd JVM to use
+JVM_CMD="$(get_property jvm\\.cmd)"
 if [ -z "$JAVA_CMD" ]; then
   JVM_CMD="java"
 fi
 
+# jvm.args Arguments to pass to the jvm
+JVM_ARGS="$(get_property jvm\\.args)"
 if [ -z "$JVM_ARGS" ]; then
   JVM_ARGS="-showversion"
 fi
 
+LOGGING_ARGS="$(get_property jvm\\.logging)"
+if [ -z "$LOGGING_ARGS" ]; then
+  LOGGING_PROPERTIES="$RELEASE_DIR"/logging.properties
+  if [ -f "$DISCOVERY_DIR"/logging.properties ]; then
+    LOGGING_PROPERTIES="$DISCOVERY_DIR"/logging.properties
+  fi
+  LOGGING_ARGS="-Djava.util.logging.config.file=$LOGGING_PROPERTIES"
+  unset LOGGING_PROPERTIES
+fi
+
+# jvm.memory = Maximum amount of memory (in MB) the engine can use
+JVM_MEMORY="$(get_property jvm\\.memory)"
 if [ -n "$JVM_MEMORY" ]; then
   JVM_ARGS="$JVM_ARGS -Xmx${JVM_MEMORY}m"
 fi
 unset JVM_MEMORY
 
+
+datatool_bind_address=$(get_property bind_address)
+datatool_http_port=$(get_property http_port)
+datatool_bind_address=$(get_property bind_address)
+datatool_https_port=$(get_property https_port)
+datatool_keystore_file=$(get_property keystore_file)
+datatool_keystore_pass=$(get_property keystore_pass)
+datatool_key_pass=$(get_property key_pass)
+datatool_truststore_file=$(get_property truststore_file)
+datatool_truststore_pass=$(get_property truststore_pass)
+datatool_logging_properties=$(get_property logging_properties)
+
 # Build command line arguments
-if [ -n "$DATATOOL_BIND_ADDRESS" ]; then
-  DATATOOL_ARGS="$DATATOOL_ARGS --bind-address $DATATOOL_BIND_ADDRESS"
+if [ -n "$datatool_bind_address" ]; then
+  DATATOOL_ARGS="$DATATOOL_ARGS --bind-address $datatool_bind_address"
 fi
-if [ -n "$DATATOOL_HTTP_PORT" ]; then
-  DATATOOL_ARGS="$DATATOOL_ARGS --port $DATATOOL_HTTP_PORT"
+if [ -n "$datatool_http_port" ]; then
+  DATATOOL_ARGS="$DATATOOL_ARGS --port $datatool_http_port"
 fi
-if [ -n "$DATATOOL_HTTPS_PORT" ]; then
-  DATATOOL_ARGS="$DATATOOL_ARGS --https-port $DATATOOL_HTTPS_PORT"
+if [ -n "$datatool_https_port" ]; then
+  DATATOOL_ARGS="$DATATOOL_ARGS --https-port $datatool_https_port"
 fi
-if [ -n "$DATATOOL_KEYSTORE_FILE" ]; then
-  DATATOOL_ARGS="$DATATOOL_ARGS --keystore-file $DATATOOL_KEYSTORE_FILE"
+if [ -n "$datatool_keystore_file" ]; then
+  DATATOOL_ARGS="$DATATOOL_ARGS --keystore-file $datatool_keystore_file"
 fi
-if [ -n "$DATATOOL_KEYSTORE_PASS" ]; then
-  DATATOOL_ARGS="$DATATOOL_ARGS --keystore-pass $DATATOOL_KEYSTORE_PASS"
+if [ -n "$datatool_keystore_pass" ]; then
+  DATATOOL_ARGS="$DATATOOL_ARGS --keystore-pass $datatool_keystore_pass"
 fi
-if [ -n "$DATATOOL_KEY_PASS" ]; then
-  DATATOOL_ARGS="$DATATOOL_ARGS --key-pass $DATATOOL_KEY_PASS"
+if [ -n "$datatool_key_pass" ]; then
+  DATATOOL_ARGS="$DATATOOL_ARGS --key-pass $datatool_key_pass"
 fi
-if [ -n "$DATATOOL_TRUSTSTORE_FILE" ]; then
-  DATATOOL_ARGS="$DATATOOL_ARGS --truststore-file $DATATOOL_TRUSTSTORE_FILE"
+if [ -n "$datatool_truststore_file" ]; then
+  DATATOOL_ARGS="$DATATOOL_ARGS --truststore-file $datatool_truststore_file"
 fi
-if [ -n "$DATATOOL_TRUSTSTORE_PASS" ]; then
-  DATATOOL_ARGS="$DATATOOL_ARGS --truststore-pass $DATATOOL_TRUSTSTORE_PASS"
+if [ -n "$datatool_truststore_pass" ]; then
+  DATATOOL_ARGS="$DATATOOL_ARGS --truststore-pass $datatool_truststore_pass"
 fi
 
 if [ -z "$DATATOOL_LOGGING_PROPERTIES" ]; then
diff --git a/stage/init-script/init.d/discovery_datatool b/stage/init-script/init.d/discovery_datatool
--- a/stage/init-script/init.d/discovery_datatool
+++ b/stage/init-script/init.d/discovery_datatool
@@ -34,34 +34,16 @@ if [ ! -d "$DATATOOL_DIR" ]; then
   echo >&2 "DATATOOL_DIR is missing: $DATATOOL_DIR"
   exit 1
 fi
-if [ ! -f "$DATATOOL_DIR/discovery_datatool.xml" ]; then
-  echo >&2 "Discovery properties file is missing: $DATATOOL_DIR/discovery_datatool.xml"
+if [ ! -f "$DATATOOL_DIR/datatool.properties" ]; then
+  echo >&2 "Discovery data tool properties file is missing: $DATATOOL_DIR/datatool.properties"
   exit 1
 fi
 
 cd "$DATATOOL_DIR"
 if [ "$USER" != "$DATATOOL_USER" ]; then
   su -l "$DATATOOL_USER" \
-    -c "env DATATOOL_DIR=\"$DATATOOL_DIR\" RELEASE_DIR=\"$RELEASE_DIR\" \
-      JVM_MEMORY=\"$JVM_MEMORY\" \
-      DATATOOL_BIND_ADDRESS=\"$DATATOOL_BIND_ADDRESS\" \
-      DATATOOL_HTTP_PORT=\"$DATATOOL_HTTP_PORT\"\
-      DATATOOL_HTTPS_PORT=\"$DATATOOL_HTTPS_PORT\"\
-      DATATOOL_KEYSTORE_FILE=\"$DATATOOL_KEYSTORE_FILE\"\
-      DATATOOL_KEYSTORE_PASS=\"$DATATOOL_KEYSTORE_PASS\"\
-      DATATOOL_KEY_PASS=\"$DATATOOL_KEY_PASS\"\
-      DATATOOL_TRUSTSTORE_FILE=\"$DATATOOL_TRUSTSTORE_FILE\"\
-      DATATOOL_TRUSTSTORE_PASS=\"$DATATOOL_TRUSTSTORE_PASS\"\
-      DATATOOL_LOGGING_PROPERTIES=\"$DATATOOL_LOGGING_PROPERTIES\"\
-      \"$RELEASE_DIR\"/bin/discovery_datatool $*"
+    -c "env DATATOOL_DIR=\"$DATATOOL_DIR\" RELEASE_DIR=\"$RELEASE_DIR\" \"$RELEASE_DIR\"/bin/discovery_datatool $*"
 else
-  export DATATOOL_DIR RELEASE_DIR JVM_MEMORY \
-    DATATOOL_BIND_ADDRESS DATATOOL_HTTP_PORT DATATOOL_HTTPS_PORT \
-    DATATOOL_KEYSTORE_FILE \
-    DATATOOL_KEYSTORE_PASS \
-    DATATOOL_KEY_PASS \
-    DATATOOL_TRUSTSTORE_FILE \
-    DATATOOL_TRUSTSTORE_PASS \
-    DATATOOL_LOGGING_PROPERTIES \
+  export DATATOOL_DIR RELEASE_DIR
   "$RELEASE_DIR/bin/discovery_datatool" $*
 fi
